# Site settings
title: گیک لایف
author: محمدامین
email: mamins1376@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  آموزش، نقد و بررسی، معرفی و ...
baseurl: "/weblog" # the subpath of your site, e.g. /blog/
url: "http://mamins1376.github.io/" # the base hostname & protocol for your site
github_username:  mamins1376

# Build settings
markdown: kramdown

comments: true
encoding: utf-8
permalink: /:year/:month/:title
paginate: 5
paginate_path: "/p:num/"
timezone: Asia/Tehran
